Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1: Code-Review-1
> > > 
> > > well... compiling, not linking.
> > 
> > Cc objects/haiku/riscv64/release/system/libroot/posix/glibc/arch/riscv64/s_copysignl.o 
> > ../src/haiku/src/system/libroot/posix/glibc/arch/generic/longdouble/128bit/s_copysignl.c:31:11: error: conflicting types for '__copysignl'
> >  _Float128 __copysignl(_Float128 x, _Float128 y)

Since the addition of _Float128, math_private.h needs an update.

Patch-set: 1
Reviewer: Gerrit User 1000023 <1000023@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Code-Review=0