Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Where do the previous definition of TRACE or ASSERT come from? I expect that these shouldn't be defined in public header files because we define them everywhere in a similar way, to allow to easily enable tracing for just select parts of the OS.
> 
> So it would possibly be better to remove the other definitions of the macros, instead?

It was only ASSERT causing the error.

I built with: jam -q -j7 @nightly-raw

../src/add-ons/kernel/file_systems/ext2/DirectoryIterator.cpp:26: error: "ASSERT" redefined [-Werror]
 # define ASSERT(x) ;
 
In file included from ../headers/private/kernel/util/DoublyLinkedList.h:14,
                 from ../src/add-ons/kernel/file_systems/ext2/Transaction.h:13,
                 from ../src/add-ons/kernel/file_systems/ext2/DirectoryIterator.h:13,
                 from ../src/add-ons/kernel/file_systems/ext2/DirectoryIterator.cpp:7:
../headers/private/kernel/debug.h:65: note: this is the location of the previous definition
 # define ASSERT(x)      ASSERT_ALWAYS(x)

To me this looks like debug mechanism I would prefer not to touch.

Patch-set: 2