Update patch set 2
Patch Set 2: Verified-1

FAILED build rebasing over hrev55361

x86_64: OK, with 43 new problems
src/apps/poorman/libhttpd/libhttpd.c:542:'err451form' defined but not used [-Wunused-variable]
src/apps/poorman/libhttpd/libhttpd.c:1616:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/apps/poorman/libhttpd/libhttpd.c:2617:comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
src/apps/poorman/libhttpd/libhttpd.c:2872:'nameptrs' may be used uninitialized in this function [-Wmaybe-uninitialized]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%ld' expects argument of type 'long int', but argument 4 has type 'long long int' [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%lld' expects argument of type 'long long int', but argument 5 has type 'char *' [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%s' expects a matching 'char *' argument [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%s' expects argument of type 'char *', but argument 3 has type 'long int' [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:3076:assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/apps/poorman/libhttpd/libhttpd.c:3076:implicit declaration of function 'build_env' [-Wimplicit-function-declaration]
src/apps/poorman/libhttpd/libhttpd.c:3080:assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
...

x86_gcc2h: 

   ...failed Link objects/haiku/<arch>/release/apps/poorman/PoorMan ...

https://haiku.movingborders.es/testbuild/I23fdf0f9910089aa8e24bb66ed7fb49b065b5577/2/hrev55361
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead  of uses. The full log provides a bit more context.

Patch-set: 2
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=-1