Update patch set 4
Patch Set 4: Verified+1

Build OK with 20 new problems rebasing over hrev55362, fixes previous version [x86_64, x86_gcc2h]

all:
src/apps/poorman/libhttpd/libhttpd.c:542:'err451form' defined but not used [-Wunused-variable]
src/apps/poorman/libhttpd/libhttpd.c:1616:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/apps/poorman/libhttpd/libhttpd.c:2617:comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
src/apps/poorman/libhttpd/libhttpd.c:3079:"/*" within comment [-Wcomment]
src/apps/poorman/libhttpd/libhttpd.c:3146:"/*" within comment [-Wcomment]
src/apps/poorman/libhttpd/libhttpd.c:3228:comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
src/apps/poorman/libhttpd/libhttpd.c:3267:"/*" within comment [-Wcomment]
src/apps/poorman/libhttpd/libhttpd.c:3418:implicit declaration of function 'closelog'; did you mean 'closedir'? [-Wimplicit-function-declaration]
src/apps/poorman/libhttpd/libhttpd.c:4248:comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
src/apps/poorman/libhttpd/libhttpd.c:4276:comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
src/apps/poorman/libhttpd/tdate_parse.c:133:passing argument 2 of 'strlong_search' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
...

x86_64:
src/apps/poorman/libhttpd/libhttpd.c:2872:'nameptrs' may be used uninitialized in this function [-Wmaybe-uninitialized]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%ld' expects argument of type 'long int', but argument 4 has type 'long long int' [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%lld' expects argument of type 'long long int', but argument 5 has type 'char *' [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%s' expects a matching 'char *' argument [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:2983:format '%s' expects argument of type 'char *', but argument 3 has type 'long int' [-Wformat=]
src/apps/poorman/libhttpd/libhttpd.c:3593:'cgi' defined but not used [-Wunused-function]

x86_gcc2h:
src/apps/poorman/libhttpd/libhttpd.c:2728:`names' might be used uninitialized in this function
src/apps/poorman/libhttpd/libhttpd.c:2729:`nameptrs' might be used uninitialized in this function
src/apps/poorman/libhttpd/libhttpd.c:2986:format argument is not a pointer (arg 3)
src/apps/poorman/libhttpd/libhttpd.c:2986:long int format, different type arg (arg 4)
src/apps/poorman/libhttpd/libhttpd.c:2986:long long int format, pointer arg (arg 5)
src/apps/poorman/libhttpd/libhttpd.c:2986:too few arguments for format
src/apps/poorman/libhttpd/libhttpd.c:3399:`envp' might be used uninitialized in this function
src/apps/poorman/libhttpd/libhttpd.c:3594:`cgi' defined but not used

https://haiku.movingborders.es/testbuild/I23fdf0f9910089aa8e24bb66ed7fb49b065b5577/4/hrev55362
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead  of uses. The full log provides a bit more context.

Patch-set: 4
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=+1