Update patch set 3
Patch Set 3: Verified+1

Build OK with 341 new problems rebasing over hrev58812, fixes previous version [x86_64, x86_gcc2h, riscv64, arm, arm64]

all:
src/system/libroot/posix/glibc/include/not-cancel.h:34:'pipe_fds[1]' may be used uninitialized [-Wmaybe-uninitialized]
src/system/libroot/posix/glibc/libio/fcloseall.c:31:no previous prototype for '__fcloseall' [-Wmissing-prototypes]
src/system/libroot/posix/glibc/libio/flockfile.c:43:'flockfile' specifies less restrictive attribute than its target '_IO_flockfile': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/libio/flockfile.c:44:'funlockfile' specifies less restrictive attribute than its target '_IO_funlockfile': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/libio/flockfile.c:45:'ftrylockfile' specifies less restrictive attribute than its target '_IO_ftrylockfile': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/libio/fmemopen.c:200:no previous prototype for 'fmemopen' [-Wmissing-prototypes]
src/system/libroot/posix/glibc/libio/fwscanf.c:26:no previous prototype for '__fwscanf' [-Wmissing-prototypes]
src/system/libroot/posix/glibc/libio/genops.c:49:'flush_cleanup' defined but not used [-Wunused-function]
src/system/libroot/posix/glibc/libio/getc_u.c:33:no previous prototype for '__getc_unlocked' [-Wmissing-prototypes]
src/system/libroot/posix/glibc/libio/iofdopen.c:187:'__new_fdopen' specifies less restrictive attribute than its target '_IO_new_fdopen': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/libio/iopopen.c:99:'unlock' defined but not used [-Wunused-function]
...

x86_64:
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'long unsigned int' and 'ssize_t' {aka 'long int'} [-Wsign-compare]
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'long int' [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'long int' to 'size_t' {aka 'long unsigned int'} due to unsignedness of other operand [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'ssize_t' {aka 'long int'} to 'long unsigned int' due to unsignedness of other operand [-Wsign-compare]
src/system/libroot/posix/glibc/libio/fileops.c:267:unused variable 'cs' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/fileops.c:640:unused variable 'st' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/iofwrite.c:49:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/system/libroot/posix/glibc/libio/iofwrite_u.c:51:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/system/libroot/posix/glibc/stdio-common/getline.c:29:implicit declaration of function '__getdelim' [-Wimplicit-function-declaration]

x86_gcc2h:
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'long unsigned int' and 'ssize_t' {aka 'long int'} [-Wsign-compare]
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'long int' [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'long int' to 'size_t' {aka 'long unsigned int'} due to unsignedness of other operand [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'ssize_t' {aka 'long int'} to 'long unsigned int' due to unsignedness of other operand [-Wsign-compare]
src/system/libroot/posix/glibc/libio/fcloseall.c:32:no previous prototype for `__fcloseall'
src/system/libroot/posix/glibc/libio/fileops.c:267:unused variable 'cs' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/fileops.c:267:unused variable `cs'
src/system/libroot/posix/glibc/libio/fileops.c:640:unused variable 'st' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/fileops.c:640:unused variable `st'
src/system/libroot/posix/glibc/libio/fileops.c:860:comparison between signed and unsigned
src/system/libroot/posix/glibc/libio/fmemopen.c:201:no previous prototype for `fmemopen'
src/system/libroot/posix/glibc/libio/fwscanf.c:27:no previous prototype for `__fwscanf'
src/system/libroot/posix/glibc/libio/genops.c:50:`flush_cleanup' defined but not used
...

riscv64:
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'long unsigned int' and 'ssize_t' {aka 'long int'} [-Wsign-compare]
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'long int' [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'long int' to 'size_t' {aka 'long unsigned int'} due to unsignedness of other operand [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'ssize_t' {aka 'long int'} to 'long unsigned int' due to unsignedness of other operand [-Wsign-compare]
src/system/libroot/posix/glibc/libio/fileops.c:267:unused variable 'cs' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/fileops.c:640:unused variable 'st' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/iofwrite.c:49:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/system/libroot/posix/glibc/libio/iofwrite_u.c:51:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/system/libroot/posix/glibc/stdio-common/getline.c:29:implicit declaration of function '__getdelim' [-Wimplicit-function-declaration]

arm:
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'long unsigned int' and 'ssize_t' {aka 'long int'} [-Wsign-compare]
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'long int' [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'long int' to 'size_t' {aka 'long unsigned int'} due to unsignedness of other operand [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'ssize_t' {aka 'long int'} to 'long unsigned int' due to unsignedness of other operand [-Wsign-compare]
src/system/libroot/posix/glibc/arch/generic/s_cacos.c:39:'__cacosl' specifies less restrictive attribute than its target '__cacos': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/arch/generic/s_casin.c:64:'__casinl' specifies less restrictive attribute than its target '__casin': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/arch/generic/s_casinh.c:82:'__casinhl' specifies less restrictive attribute than its target '__casinh': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/arch/generic/s_cexp.c:125:'__cexpl' specifies less restrictive attribute than its target '__cexp': 'nothrow' [-Wmissing-attributes]
src/system/libroot/posix/glibc/arch/generic/s_clog.c:63:'__clogl' specifies less restrictive attribute than its target '__clog': 'nothrow' [-Wmissing-attributes]
...

arm64:
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'long unsigned int' and 'ssize_t' {aka 'long int'} [-Wsign-compare]
headers/posix/sys/param.h:20:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'long int' [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'long int' to 'size_t' {aka 'long unsigned int'} due to unsignedness of other operand [-Wsign-compare]
headers/posix/sys/param.h:20:operand of '?:' changes signedness from 'ssize_t' {aka 'long int'} to 'long unsigned int' due to unsignedness of other operand [-Wsign-compare]
src/system/libroot/posix/glibc/libio/fileops.c:267:unused variable 'cs' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/fileops.c:640:unused variable 'st' [-Wunused-variable]
src/system/libroot/posix/glibc/libio/iofwrite.c:49:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/system/libroot/posix/glibc/libio/iofwrite_u.c:51:comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
src/system/libroot/posix/glibc/stdio-common/getline.c:29:implicit declaration of function '__getdelim' [-Wimplicit-function-declaration]

https://haiku.movingborders.es/testbuild/I73ebde80d314460174d344ba1e2960807ad4717b/3/hrev58812
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 3
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=+1, 46f16ffefe2302a76ec5b5f960e73a35f065f2bf