Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> src/add-ons/control_look/BeControlLook/BeControlLook.cpp:570:19: error: 'B_KNOB_NONE' was not declared in this scope
>   if (knobStyle != B_KNOB_NONE) {
>                    ^~~~~~~~~~~
> src/add-ons/control_look/BeControlLook/BeControlLook.cpp:570:19: note: suggested alternative: 'B_ANY_NODE'
>   if (knobStyle != B_KNOB_NONE) {
>                    ^~~~~~~~~~~
>                    B_ANY_NODE
> src/add-ons/control_look/BeControlLook/BeControlLook.cpp:576:20: error: 'B_KNOB_DOTS' was not declared in this scope
>    if (knobStyle == B_KNOB_DOTS) {
>                     ^~~~~~~~~~~
> src/add-ons/control_look/BeControlLook/BeControlLook.cpp:576:20: note: suggested alternative: 'B_KEY_DOWN'
>    if (knobStyle == B_KNOB_DOTS) {
>                     ^~~~~~~~~~~
>                     B_KEY_DOWN
> src/add-ons/control_look/BeControlLook/BeControlLook.cpp:605:27: error: 'B_KNOB_LINES' was not declared in this scope
>    } else if (knobStyle == B_KNOB_LINES) {
>                            ^~~~~~~~~~~~
> src/add-ons/control_look/BeControlLook/BeControlLook.cpp:605:27: note: suggested alternative: 'B_NO_TINT'
>    } else if (knobStyle == B_KNOB_LINES) {
>                            ^~~~~~~~~~~~
>                            B_NO_TINT

There’s 3 patches that are needed for this to work right all submitted together. These definitions are defined in the first patch. The second patch updates Appearance prefs to add knob setting and also updates how the fake scroll bar is drawn to use the new methods defined in the first patch.

Patch-set: 2
Reviewer: Gerrit User 1000013 <1000013@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>