Update patch set 8
Patch Set 8: Code-Review-1

Hm. suddenly getting

BootLd objects/haiku/riscv64/release/system/boot/efi/boot_loader_efi 
/home/kallisti5/Code/haiku/generated.riscv64/cross-tools-riscv64/bin/riscv64-unknown-haiku-ld: objects/haiku/riscv64/release/system/boot/platform/efi/efi/boot_platform_efi.o: in function `smp_get_current_cpu':
(.text+0x4dc6): undefined reference to `strncpy'


Need to investigate that.  I guess efi platform_loader has no standard libs? Thought openfirmware did something similar with string.h stuff.

Patch-set: 8
Reviewer: Gerrit User 1000000 <1000000@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Code-Review=-1