Update patch set 1
Patch Set 1: Verified-1

FAILED build rebasing over hrev55950 [riscv64, x86_gcc2h]

x86_gcc2h: 

   ...failed As objects/haiku/<arch>/release/system/libroot/unwind/UnwindRegistersRestore.o ...
   ...failed As objects/haiku/<arch>/release/system/libroot/unwind/UnwindRegistersSave.o ...
   ...failed C++ objects/haiku/<arch>/release/system/libroot/unwind/libunwind.o ...
   ...failed Cc objects/haiku/<arch>/release/system/libroot/unwind/UnwindLevel1-gcc-ext.o ...
   ...failed Cc objects/haiku/<arch>/release/system/libroot/unwind/UnwindLevel1.o ...

riscv64: 

   ...failed Link objects/haiku/<arch>/release/system/libroot/libroot.so ...

x86_64: OK, with 13 new problems
src/system/libroot/unwind/libgcc.c:4:no previous prototype for '__umoddi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:5:no previous prototype for '__udivdi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:6:no previous prototype for '__udivmoddi4' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:7:no previous prototype for '__divdi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:8:no previous prototype for '__moddi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:9:conflicting types for built-in function '__mulxc3'; expected '_Complex long double(long double,  long double,  long double,  long double)' [-Wbuiltin-declaration-mismatch]
src/system/libroot/unwind/libgcc.c:10:conflicting types for built-in function '__muldc3'; expected '_Complex double(double,  double,  double,  double)' [-Wbuiltin-declaration-mismatch]
src/system/libroot/unwind/libgcc.c:11:conflicting types for built-in function '__mulsc3'; expected '_Complex float(float,  float,  float,  float)' [-Wbuiltin-declaration-mismatch]
src/system/libroot/unwind/libgcc.c:12:no previous prototype for '__divmoddi4' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:13:no previous prototype for '__clz_tab' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:14:no previous prototype for '__udivmodti4' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:15:no previous prototype for '__udivti3' [-Wmissing-prototypes]
...

https://haiku.movingborders.es/testbuild/Ic9e51cdbf89db91daf5d0cb62319e20c4c7c6c12/1/hrev55950
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 1
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=-1