Update patch set 4
Patch Set 4:

Looks like sources are missing:

../src/system/kernel/UserTimer.cpp:25:11: fatal error: user_timer_defs_compat.h: No such file or directory

I don't see user_timer_defs_compat.h laying around anywhere in Github.

Patch-set: 4
Reviewer: Gerrit User 1000000 <1000000@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>