Update patch set 6
Patch Set 6:

I fixed a couple of compilation errors that sort of slipped out, I think I've made those sorts of mistakes before in C++ code and I'm a bit rusty (pun unintended), so yeah, I think I fixed them sufficiently. Didn't have a clue as to why x86_gcc2 would break, but the compiler could not compile AboutSystem.cpp because of:

```
In file included from /s/src/apps/aboutsystem/AboutSystem.cpp:13:
/s/src/apps/aboutsystem/AboutSystem.h:68: `::string' undeclared (first use here)
/s/src/apps/aboutsystem/AboutSystem.h:68: template argument 1 is invalid
/s/src/apps/aboutsystem/AboutSystem.h:68: template argument 1 is invalid
/s/src/apps/aboutsystem/AboutSystem.h:68: template argument 3 is invalid
/s/src/apps/aboutsystem/AboutSystem.h:68: confused by earlier errors, bailing out
cpp0: output pipe has been closed
```

I hope that I fixed this with my latest patch set, now I'm just waiting.

(Jeez, the Commit checker robot is immensely useful.)

Patch-set: 6