Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > > Patch Set 1: Code-Review-1
> > > > 
> > > > well... compiling, not linking.
> > > 
> > > Cc objects/haiku/riscv64/release/system/libroot/posix/glibc/arch/riscv64/s_copysignl.o 
> > > ../src/haiku/src/system/libroot/posix/glibc/arch/generic/longdouble/128bit/s_copysignl.c:31:11: error: conflicting types for '__copysignl'
> > >  _Float128 __copysignl(_Float128 x, _Float128 y)
> 
> Since the addition of _Float128, math_private.h needs an update.

Importing the latest math_private.h (and math_private_calls.h) from glibc gets us a bit further, but still conflicts.  


Cc objects/haiku/riscv64/release/system/libroot/posix/glibc/arch/riscv64/sincos32.o 
../src/haiku/src/system/libroot/posix/glibc/arch/generic/sincos32.c:189:8: error: conflicting types for '__mpsin'
 double __mpsin(double x, double dx) {
        ^~~~~~~
In file included from ../src/haiku/src/system/libroot/posix/glibc/arch/generic/sincos32.c:46:0:
../src/haiku/src/system/libroot/posix/glibc/math/math_private.h:236:15: note: previous declaration of '__mpsin' was here
 extern double __mpsin (double __x, double __dx, bool __range_reduce);
               ^~~~~~~
../src/haiku/src/system/libroot/posix/glibc/arch/generic/sincos32.c:207:8: error: conflicting types for '__mpcos'
 double __mpcos(double x, double dx) {
        ^~~~~~~
In file included from ../src/haiku/src/system/libroot/posix/glibc/arch/generic/sincos32.c:46:0:
../src/haiku/src/system/libroot/posix/glibc/math/math_private.h:237:15: note: previous declaration of '__mpcos' was here
 extern double __mpcos (double __x, double __dx, bool __range_reduce);
               ^~~~~~~
../src/haiku/src/system/libroot/posix/glibc/arch/generic/sincos32.c:278:8: warning: no previous prototype for '__mpsin1' [-Wmissing-prototypes]
 double __mpsin1(double x)
        ^~~~~~~~
../src/haiku/src/system/libroot/posix/glibc/arch/generic/sincos32.c:317:8: warning: no previous prototype for '__mpcos1' [-Wmissing-prototypes]
 double __mpcos1(double x)

Patch-set: 1