Update patch set 1
Patch Set 1: Code-Review+1

ok. here's the worst of where i'm at getting cpu* in the bootloader:


In file included from ../headers/private/kernel/arch/cpu.h:44,
                 from ../headers/private/kernel/arch/arm/arch_kernel.h:8,
                 from ../headers/private/kernel/kernel.h:14,
                 from ../headers/private/kernel/arch/arm/arch_thread_types.h:8,
                 from ../headers/private/kernel/arch/thread_types.h:8,
                 from ../headers/private/kernel/thread_types.h:15,
                 from ../headers/private/kernel/arch/thread.h:12,
                 from ../headers/private/kernel/thread.h:17,
                 from ../headers/private/kernel/elf.h:13,
                 from ../src/system/boot/platform/efi/arch/arm/relocation_func.cpp:40:
../headers/private/kernel/boot/platform/efi/arch_cpu.h:16:10: error: conflicting declaration of C function 'status_t arch_cpu_init()'

so.. arch_thread_types (on every cpu) needs the iframe definition, which it gets from kernel.h -> arch_kernel.h -> cpu.h -> arch_cpu.h

iframe is defined in arch_cpu.h on every architecture:
 ../headers/private/kernel/arch/arm/arch_cpu.h:struct iframe {

Thus, us including elf support code in the bootloader for relocations, always sends us to conflicting kernel arch_cpu headers.

Solutions:

  * Refactor all of our kernel CPU code, moving iframe definitions "somewhere else"
  * elf.h *can* be short circuited from thread.h to thread_types.h for "Team", but it doesn't solve the issue.
  * just stick with patchset 1

Patch-set: 1
Reviewer: Gerrit User 1000000 <1000000@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Code-Review=+1