Update patch set 3
Patch Set 3:

Fixed merge conflict. Currently build fails:

C++ objects/haiku/x86_64/release/system/boot/loader/file_systems/bfs/bios_ia32/bfs.o 
In file included from ../src/system/kernel/debug/safemode_settings.cpp:18:
../headers/private/kernel/util/syscall_args.h: In function 'status_t copy_ref_var_from_user(T*, T&)':
../headers/private/kernel/kernel.h:35:46: error: 'USER_TOP' was not declared in this scope
 # define IS_USER_ADDRESS(x)  ((addr_t)(x) <= USER_TOP)

Patch-set: 3
Reviewer: Gerrit User 1000172 <1000172@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>