Update patch set 2
Patch Set 2: Verified+1

Build OK with 7 new problems rebasing over hrev58146, fixes previous version [arm, x86_gcc2h, arm64, riscv64, x86_64]

all:
src/libs/libsolv/ext/solv_xfopen.c:8:"_DEFAULT_SOURCE" redefined
src/system/libroot/posix/musl/search/tdestroy.c:6:no previous prototype for 'tdestroy' [-Wmissing-prototypes]

arm:
src/libs/libsolv/solv/repodata.c:309:assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/libs/libsolv/solv/repodata.c:309:implicit declaration of function 'strchrnul'; did you mean 'strchr'? [-Wimplicit-function-declaration]

x86_gcc2h:
src/libs/libsolv/solv/repodata.c:309:assignment makes pointer from integer without a cast
src/libs/libsolv/solv/repodata.c:309:assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/libs/libsolv/solv/repodata.c:309:implicit declaration of function 'strchrnul'; did you mean 'strchr'? [-Wimplicit-function-declaration]
src/libs/libsolv/solv/repodata.c:309:implicit declaration of function `strchrnul'
src/system/libroot/posix/musl/search/tdestroy.c:7:no previous prototype for `tdestroy'

riscv64:
src/libs/libsolv/solv/repodata.c:309:assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/libs/libsolv/solv/repodata.c:309:implicit declaration of function 'strchrnul'; did you mean 'strchr'? [-Wimplicit-function-declaration]

arm64:
src/libs/libsolv/solv/repodata.c:309:assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/libs/libsolv/solv/repodata.c:309:implicit declaration of function 'strchrnul'; did you mean 'strchr'? [-Wimplicit-function-declaration]

x86_64:
src/libs/libsolv/solv/repodata.c:309:assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/libs/libsolv/solv/repodata.c:309:implicit declaration of function 'strchrnul'; did you mean 'strchr'? [-Wimplicit-function-declaration]

https://haiku.movingborders.es/testbuild/I5c7baf40b7fb37913e24279589fc1ae706448a45/2/hrev58146
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 2
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=+1, 14c415511ae7b2b79473cd364f6292a2c5aafefa