Update patch set 7
Patch Set 7: Verified+1

Build OK with 1 new problems rebasing over hrev57570 [riscv64, x86_64, arm, x86_gcc2h, arm64]

all:
src/tools/fs_shell/fssh.cpp:431:too many arguments for format [-Wformat-extra-args]

https://haiku.movingborders.es/testbuild/Ice48680d289261a43e82a4189a2bc5619d4f5d9c/7/hrev57570
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 7
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=+1, 82cc313b726ca9f8f72dd34f49b8bdcbb08eb179