Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > I'd love to keep the *cpu.* naming, however given the tight integration between kernel headers+sources and bootloader headers+sources, every time i've tried it has ended in a horrible mess (which is why the cpu -> arch_cpu refactor was never done in EFI during my last commits)
> > 
> > Why in the world is there a tight integration? There shouldn't be; and indeed your find shows that there are arch_cpu files in u-boot, and cpu files in every other bootloader, so either this is an EFI-specific problem or it isn't one at all...
> 
> The main offender seems to be:
> https://git.haiku-os.org/haiku/tree/src/system/boot/platform/efi/Jamfile#n6
> 
> it appears the intent of src/system/boot/arch is to prevent the bootloader and kernel code from mingling directly.
> 
> Let me try and figure out the reason for line 6 above.

Line 6 can be removed, which does solve some of the architecture header collisions.

But, then we run into lovely things like this:

In file included from ../headers/private/kernel/arch/cpu.h:44,
                 from ../headers/private/kernel/arch/arm/arch_kernel.h:8,
                 from ../headers/private/kernel/kernel.h:14,
                 from ../src/system/boot/platform/efi/arch/arm/arch_timer.cpp:14:
../headers/private/kernel/boot/platform/efi/arch_cpu.h:16:10: error: conflicting declaration of C function 'status_t arch_cpu_init()'
 status_t arch_cpu_init(void);
          ^~~~~~~~~~~~~
In file included from ../headers/private/kernel/arch/arm/arch_kernel.h:8,
                 from ../headers/private/kernel/kernel.h:14,
                 from ../src/system/boot/platform/efi/arch/arm/arch_timer.cpp:14:
../headers/private/kernel/arch/cpu.h:26:10: note: previous declaration 'status_t arch_cpu_init(kernel_args*)'
 status_t arch_cpu_init(struct kernel_args *args);
          ^~~~~~~~~~~~~
In file included from ../headers/private/kernel/arch/cpu.h:44,
                 from ../headers/private/kernel/arch/arm/arch_kernel.h:8,
                 from ../headers/private/kernel/kernel.h:14,
                 from ../src/system/boot/platform/efi/arch/arm/arch_timer.cpp:14:

Patch-set: 1
Reviewer: Gerrit User 1000000 <1000000@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>