Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review-1
> 
> well... compiling, not linking.

Cc objects/haiku/riscv64/release/system/libroot/posix/glibc/arch/riscv64/s_copysignl.o 
../src/haiku/src/system/libroot/posix/glibc/arch/generic/longdouble/128bit/s_copysignl.c:31:11: error: conflicting types for '__copysignl'
 _Float128 __copysignl(_Float128 x, _Float128 y)
           ^~~~~~~~~~~
In file included from ../src/haiku/src/system/libroot/posix/glibc/arch/generic/longdouble/128bit/s_copysignl.c:28:0:
../src/haiku/src/system/libroot/posix/glibc/math/math_private.h:288:20: note: previous declaration of '__copysignl' was here
 extern long double __copysignl (long double, long double);
                    ^~~~~~~~~~~

So, weird conflicting types whenever I include s_copysignl.c (which is needed)

Patch-set: 1