Update patch set 2
Patch Set 2:

> > ../src/add-ons/kernel/file_systems/ext2/DirectoryIterator.cpp:26: error: "ASSERT" redefined [-Werror]
> >  # define ASSERT(x) ;
> >  
> > In file included from ../headers/private/kernel/util/DoublyLinkedList.h:14,
> >                  from ../src/add-ons/kernel/file_systems/ext2/Transaction.h:13,
> >                  from ../src/add-ons/kernel/file_systems/ext2/DirectoryIterator.h:13,
> >                  from ../src/add-ons/kernel/file_systems/ext2/DirectoryIterator.cpp:7:
> > ../headers/private/kernel/debug.h:65: note: this is the location of the previous definition
> >  # define ASSERT(x)      ASSERT_ALWAYS(x)
> > 
> > To me this looks like debug mechanism I would prefer not to touch.
> 
> Means I think that the original ASSERT is used for kernel debugging and used in related add-ons. And therefore I think the renaming of the ext2 macros is the way to go for the ext2 add-on.

I think I would rather remove the debug.h include from DoublyLinkedList.h so that it doesn't define ASSERT for everyone.

Patch-set: 2