Update patch set 1
Patch Set 1: Verified-1

FAILED build rebasing over hrev56361 [arm64 (hrev56361 also broken), riscv64 (hrev56361 also broken)]

   ...failed Link objects/haiku/<arch>/release/system/libroot/libroot.so ...
   ...failed Link objects/haiku/<arch>/release/system/libroot/libroot_debug.so ...

x86_64 (fixes master): OK, with 7 new problems
jambuild:0:warning: using independent target <HaikuImage>/b/x86_64/./haiku.image-copy-files
jambuild:0:warning: using independent target <HaikuImage>/b/x86_64/./haiku.image-extract-files
jambuild:0:warning: using independent target <HaikuImage>/b/x86_64/./haiku.image-init-vars
jambuild:0:warning: using independent target <HaikuImage>/b/x86_64/./haiku.image-make-dirs
src/system/libroot/posix/musl/time/asctime.c:6:implicit declaration of function '__asctime_r'; did you mean 'asctime_r'? [-Wimplicit-function-declaration]
src/system/libroot/posix/musl/time/asctime.c:6:returning 'int' from a function with return type 'char *' makes pointer from integer without a cast [-Wint-conversion]
src/system/libroot/posix/musl/time/asctime_r.c:8:no previous prototype for '__asctime_r' [-Wmissing-prototypes]

x86_gcc2h (fixes master): OK, with 12 new problems
jambuild:0:warning: using independent target <HaikuImage>/b/x86_gcc2h/./haiku.image-copy-files
jambuild:0:warning: using independent target <HaikuImage>/b/x86_gcc2h/./haiku.image-extract-files
jambuild:0:warning: using independent target <HaikuImage>/b/x86_gcc2h/./haiku.image-init-vars
jambuild:0:warning: using independent target <HaikuImage>/b/x86_gcc2h/./haiku.image-make-dirs
src/system/libroot/posix/musl/time/asctime.c:6:implicit declaration of function '__asctime_r'; did you mean 'asctime_r'? [-Wimplicit-function-declaration]
src/system/libroot/posix/musl/time/asctime.c:6:implicit declaration of function `__asctime_r'
src/system/libroot/posix/musl/time/asctime.c:6:return makes pointer from integer without a cast
src/system/libroot/posix/musl/time/asctime.c:6:returning 'int' from a function with return type 'char *' makes pointer from integer without a cast [-Wint-conversion]
src/system/libroot/posix/musl/time/asctime_r.c:8:no previous prototype for '__asctime_r' [-Wmissing-prototypes]
src/system/libroot/posix/musl/time/asctime_r.c:9:no previous prototype for `__asctime_r'
src/system/libroot/posix/musl/time/time_impl.h:8:`__visibility__' attribute directive ignored
src/system/libroot/posix/musl/time/time_impl.h:9:`__visibility__' attribute directive ignored

arm (fixes master): OK, with 7 new problems
jambuild:0:warning: using independent target <HaikuImage>/b/arm/./haiku.image-copy-files
jambuild:0:warning: using independent target <HaikuImage>/b/arm/./haiku.image-extract-files
jambuild:0:warning: using independent target <HaikuImage>/b/arm/./haiku.image-init-vars
jambuild:0:warning: using independent target <HaikuImage>/b/arm/./haiku.image-make-dirs
src/system/libroot/posix/musl/time/asctime.c:6:implicit declaration of function '__asctime_r'; did you mean 'asctime_r'? [-Wimplicit-function-declaration]
src/system/libroot/posix/musl/time/asctime.c:6:returning 'int' from a function with return type 'char *' makes pointer from integer without a cast [-Wint-conversion]
src/system/libroot/posix/musl/time/asctime_r.c:8:no previous prototype for '__asctime_r' [-Wmissing-prototypes]

https://haiku.movingborders.es/testbuild/I1e7e02b27d6fee4845c81cf6f229bca0048a0e61/1/hrev56361
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 1
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000002 \u003c1000002@40b9299a-d8a8-485d-9b01-e6d3f45eefb5\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}