Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review-2
> 
> Thall shall not merge.
> 
> Resolving package dependencies ...
> ERROR: Some of the unactivated (i.e. optional) packages have the following unmet dependencies:
> gawk_x86-5.1.0-1-x86_gcc2.hpkg

Attempted fix by switching to mawk instead of gawk: https://review.haiku-os.org/c/haiku/+/3356

It is unclear where the gawk dependency comes from, however. Let me know if mawk solves things.

It would be nice to get this fixed because now, Haiku installs will be running with 3 vesions of ICU (old and new for x86 + old for gcc2) since webkit already switched to the new one.

Patch-set: 1
Reviewer: Gerrit User 1000001 <1000001@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>