Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > Can someone confirm that this still builds for x86_64? If it's broken there, the same changes will need to be done for the 64bit version.
> 
> I just did an incremental build and I got the error below:

> ERROR: Some of the unactivated (i.e. optional) packages have the following unmet dependencies:
> gawk-5.1.0-1-x86_64.hpkg

Thanks. I have switched from gawk to mawk and on 32bit this was not a problem (all other packages depend on cmd:awk and not cmd:gawk). I hope this issue will go away when we do the update for x86_64 as well. Until then we can try to have gawk@x86_64 mawk@x86_gcc2 in the package list.

Patch-set: 1
Reviewer: Gerrit User 1000001 <1000001@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>