Update patch set 1
Patch Set 1: Verified+1

Build OK with 8 new problems rebasing over hrev57208 [x86_gcc2h, x86_64]

all:
src/system/libroot/posix/musl/time/asctime_r.c:8:no previous prototype for '__asctime_r' [-Wmissing-prototypes]

x86_64:
src/system/libroot/posix/musl/time/asctime.c:6:implicit declaration of function '__asctime_r'; did you mean 'asctime_r'? [-Wimplicit-function-declaration]
src/system/libroot/posix/musl/time/asctime.c:6:returning 'int' from a function with return type 'char *' makes pointer from integer without a cast [-Wint-conversion]

x86_gcc2h:
src/system/libroot/posix/musl/time/asctime.c:6:implicit declaration of function '__asctime_r'; did you mean 'asctime_r'? [-Wimplicit-function-declaration]
src/system/libroot/posix/musl/time/asctime.c:6:implicit declaration of function `__asctime_r'
src/system/libroot/posix/musl/time/asctime.c:6:return makes pointer from integer without a cast
src/system/libroot/posix/musl/time/asctime.c:6:returning 'int' from a function with return type 'char *' makes pointer from integer without a cast [-Wint-conversion]
src/system/libroot/posix/musl/time/asctime_r.c:9:no previous prototype for `__asctime_r'
src/system/libroot/posix/musl/time/time_impl.h:8:`__visibility__' attribute directive ignored
src/system/libroot/posix/musl/time/time_impl.h:9:`__visibility__' attribute directive ignored

https://haiku.movingborders.es/testbuild/I1e7e02b27d6fee4845c81cf6f229bca0048a0e61/1/hrev57208
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 1
Tag: autogenerated:buildbot
Label: Verified=+1, d7f076f23278f69d899bc65f8756eb100bbe2d94