Update packages for OpenSSL3
For reference, shows what needs to be updated.
The other architectures will need similar updates.

Remaining problem: HaikuWebKit cannot currently be built with OpenSSL 3.

    Encountered problems:
    problem 1: nothing provides lib:libssl>=1.1 needed by haikuwebkit-1.9.11-2
      solution 1:
        - allow deinstallation of webpositive-r1~beta4_hrev57805_12_dirty-1

    /sources/haikuwebkit-HaikuWebKit-1.9.11/Source/WebCore/crypto/openssl/CryptoKeyRSAOpenSSL.cpp: In member function 'size_t WebCore::CryptoKeyRSA::keySizeInBits() const':
    /sources/haikuwebkit-HaikuWebKit-1.9.11/Source/WebCore/crypto/openssl/CryptoKeyRSAOpenSSL.cpp:168:33: warning: 'const rsa_st* EVP_PKEY_get0_RSA(const EVP_PKEY*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
      168 |     RSA* rsa = EVP_PKEY_get0_RSA(m_platformKey.get());
          |                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
    /boot/system/develop/headers/openssl/evp.h:1348:22: note: declared here
     1348 | const struct rsa_st *EVP_PKEY_get0_RSA(const EVP_PKEY *pkey);
          |                      ^~~~~~~~~~~~~~~~~
    /sources/haikuwebkit-HaikuWebKit-1.9.11/Source/WebCore/crypto/openssl/CryptoKeyRSAOpenSSL.cpp:168:33: error: invalid conversion from 'const rsa_st*' to 'RSA*' {aka 'rsa_st*'} [-fpermissive]
      168 |     RSA* rsa = EVP_PKEY_get0_RSA(m_platformKey.get());
          |                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
          |                                 |
          |                                 const rsa_st*

Fixes #18581

Change-Id: Ia6613e5e9b2b9e8dd4eed479bf620bed3c5371f0