Update patch set 4
Patch Set 4:

This broke all of the builds.

../haiku-git/src/apps/installer/InstallerApp.cpp: In member function 'virtual void InstallerApp::Quit()':
../haiku-git/src/apps/installer/InstallerApp.cpp:81:7: error: 'fInstallStatus' was not declared in this scope
   if (fInstallStatus == kFinished) {
       ^~~~~~~~~~~~~~
../haiku-git/src/apps/installer/InstallerApp.cpp:81:7: note: suggested alternative: 'InstallStatus'
   if (fInstallStatus == kFinished) {
       ^~~~~~~~~~~~~~
       InstallStatus
../haiku-git/src/apps/installer/InstallerApp.cpp:97:4: error: 'BLaunchRoster' was not declared in this scope
    BLaunchRoster().Target("firstbootprompt");
    ^~~~~~~~~~~~~
../haiku-git/src/apps/installer/InstallerApp.cpp:97:4: note: suggested alternative: 'BLocaleRoster'
    BLaunchRoster().Target("firstbootprompt");
    ^~~~~~~~~~~~~
    BLocaleRoster

Patch-set: 4
CC: Gerrit User 1000000 <1000000@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>