Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> hell.. those lines result in a build-failure anyway:
> ```
> ../src/system/kernel/vm/vm.cpp: In function 'status_t vm_page_fault(addr_t, addr_t, bool, bool, bool, bool, addr_t*)':
> ../src/system/kernel/vm/vm.cpp:4433:5: error: 'WriteTrapInfo' was not declared in this scope
>      WriteTrapInfo();
>      ^~~~~~~~~~~~~
> ../src/system/kernel/vm/vm.cpp:4441:4: error: 'WriteTrapInfo' was not declared in this scope
>     WriteTrapInfo();
>     ^~~~~~~~~~~~~
> ../src/system/kernel/vm/vm.cpp:4442:4: error: 'DoStackTrace' was not declared in this scope
>     DoStackTrace(Fp(), 0);
> ```

Just delete/comment it. It is only used for debugging output.

Patch-set: 5