Update patch set 4
Patch Set 4: Verified+1

Build OK with 1 new problems rebasing over hrev57569 [arm64, arm, x86_gcc2h, x86_64, riscv64]

all:
src/tools/fs_shell/fssh.cpp:431:too many arguments for format [-Wformat-extra-args]

https://haiku.movingborders.es/testbuild/Ice48680d289261a43e82a4189a2bc5619d4f5d9c/4/hrev57569
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 4
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=+1, 37525aaacfee58c2d0edf10a5401c2fb470fd65c