Update patch set 3
Patch Set 3: Verified-1

FAILED build rebasing over hrev56127 [riscv64, x86_gcc2h]still broken

x86_64: OK, with 16 new problems
src/system/libroot/unwind/UnwindLevel1.c:74:variable 'functionName' set but not used [-Wunused-but-set-variable]
src/system/libroot/unwind/UnwindLevel1.c:173:variable 'functionName' set but not used [-Wunused-but-set-variable]
src/system/libroot/unwind/UnwindLevel1.c:264:variable 'functionName' set but not used [-Wunused-but-set-variable]
src/system/libroot/unwind/libgcc.c:4:no previous prototype for '__umoddi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:5:no previous prototype for '__udivdi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:6:no previous prototype for '__udivmoddi4' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:7:no previous prototype for '__divdi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:8:no previous prototype for '__moddi3' [-Wmissing-prototypes]
src/system/libroot/unwind/libgcc.c:9:conflicting types for built-in function '__mulxc3'; expected '_Complex long double(long double,  long double,  long double,  long double)' [-Wbuiltin-declaration-mismatch]
src/system/libroot/unwind/libgcc.c:10:conflicting types for built-in function '__muldc3'; expected '_Complex double(double,  double,  double,  double)' [-Wbuiltin-declaration-mismatch]
src/system/libroot/unwind/libgcc.c:11:conflicting types for built-in function '__mulsc3'; expected '_Complex float(float,  float,  float,  float)' [-Wbuiltin-declaration-mismatch]
src/system/libroot/unwind/libgcc.c:12:no previous prototype for '__divmoddi4' [-Wmissing-prototypes]
...

https://haiku.movingborders.es/testbuild/Ic9e51cdbf89db91daf5d0cb62319e20c4c7c6c12/3/hrev56127
Line numbers are of rebased code, which may not match the ones in the patch. Warnings may also come from ancestor patches or be detected in macro definition instead of uses. The full log provides a bit more context.

Patch-set: 3
Tag: autogenerated:buildbot
Reviewer: Gerrit User 1000312 <1000312@40b9299a-d8a8-485d-9b01-e6d3f45eefb5>
Label: Verified=-1